name: Package to Tar.xz Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install zip tar -y

    - name: Find directories and create zips
      run: |
        find . -type d -exec bash -c 'cd "{}" && zip -r "../${PWD##*/}.zip" .' \;

    - name: Create tar.xz from zips
      run: |
        find . -name '*.zip' -exec tar -cJf packages.tar.xz {} +

    - name: Upload tar.xz artifact
      uses: actions/upload-artifact@v2
      with:
        name: package-tar.xz
        path: packages.tar.xz
