name: Create List and Zip Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install zip -y

    - name: Generate file list
      run: |
        find . -type f > file_list.txt
        jq -n 'reduce (inputs | . / "\n") as $line ({}; .[$line | rtrimstr("\r")] = 1)' file_list.txt > file_list.json

    - name: Create zip file
      run: |
        zip -r data.zip file_list.txt file_list.json

    - name: Upload zip artifact
      uses: actions/upload-artifact@v2
      with:
        name: data-zip
        path: data.zip
